version: '3'

services:
  browser:
    image: "browserless/chrome:latest"
    ports:
      - 4000:3000
    networks: 
      - youtube-scraper

  db:
    image: "mongo:4.2.5-bionic"
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: db
    volumes:
      - db:/data/db
      - ./init/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./data/:/data
    networks: 
      - youtube-scraper
  mongo-express:
    image: mongo-express
    ports:
      - 4001:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
    networks: 
      - youtube-scraper

networks:
  youtube-scraper:

volumes:
  db: